### ISSUE TITLE
Add a script for sneakersnstuff

### ISSUE THREAD

**Issue by ChbShoot** [kfichter/OpenATC#2]

**Comment by ChbShoot** [comment]
Added script but keyword search and checkout are missing

**Comment by anthony6608** [comment]
Tested and getting errors. Could possibly be caused by Captcha. Is it possible to bypass or solve in browser?

python sneakersnstuff.py 
Traceback (most recent call last):
  File "sneakersnstuff.py", line 77, in <module>
    add_to_cart(early_link, shoe_size)
  File "sneakersnstuff.py", line 49, in add_to_cart
    size_divs = form.find_all('div', { 'class':  'size-button property available'})
AttributeError: 'NoneType' object has no attribute 'find_all'
